---

- name: "Wireguard | Topology {{ topo_name }} | Tunnel | Check | Checking config"
  ansible.builtin.assert:
    that:
      - int_name | length < 16  # interface-length limitation
  tags: always
