---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml
# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml --ask-vault-pass

- name: WireGuard Site-to-Site
  hosts: all   # should be limited
  become: true
  gather_facts: yes
  roles:
    - ansibleguy.infra_wireguard
