---

- name: Wireguard | Checking config
  ansible.builtin.fail:
    msg: "The required configuration was not provided!
    Needed: 'wireguard', 'wireguard.topologies'"
  when: >
    wireguard is undefined or
    wireguard.topologies is undefined

- name: Wireguard | Skipping host => not configured in any wireguard-topology
  ansible.builtin.meta: end_host
  when: "inventory_hostname not in wireguard.topologies | flatten_hosts"

- name: Wireguard | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
